### ISSUE TITLE
Doesn't Deploy Correctly to Heroku

### ISSUE THREAD

**Issue by williambarberjr** [4GeeksAcademy/flask-rest-hello#19]
First got an error `Your Pipfile.lock (d45272) is out of date` that was solved by running  `pipenv lock`

Then I got:
`remote: Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.`

the .env file has the following code in it (including a "FLASK_APP" environment variable)

```
DB_CONNECTION_STRING=mysql+mysqlconnector://root@localhost/example
FLASK_APP_KEY="any key works"
FLASK_APP=src/main.py
FLASK_ENV=development
```

Thoughts on how I can fix this? Tried deploying with my current directory set to the src folder, this also didn't work. I'm deploying from gitpod using the provided instructions in the readme file.

**Comment by williambarberjr** [comment]
`pipenv install 'SQLAlchemy<1.4';` seems to address that issue, more on that here: https://stackoverflow.com/questions/65610809/retrieving-data-from-rds-gives-attributeerror-sqlalchemy-cimmutabledict-immuta

Now there's a new error. Here's the stack trace:
```
remote:✔ Successfully created virtual environment! 
remote: Virtualenv location: /app/.local/share/virtualenvs/app-4PlAip0Q
remote: Loading .env environment variables...
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 233, in _open_connection
remote:     self._cmysql.connect(**cnx_kwargs)
remote: _mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost' (111)
remote: 
remote: During handling of the above exception, another exception occurred:
remote: 
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
remote:     return fn()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
remote:     return _ConnectionFairy._checkout(self)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
remote:     fairy = _ConnectionRecord.checkout(pool)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
remote:     rec = pool._do_get()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
remote:     self._dec_overflow()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
remote:     with_traceback=exc_tb,
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
remote:     raise exception
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
remote:     return self._create_connection()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
remote:     return _ConnectionRecord(self)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
remote:     self.__connect(first_connect_check=True)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
remote:     pool.logger.debug("Error on connect(): %s", e)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
remote:     with_traceback=exc_tb,
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
remote:     raise exception
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
remote:     connection = pool._invoke_creator(self)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
remote:     return dialect.connect(*cargs, **cparams)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
remote:     return self.dbapi.connect(*cargs, **cparams)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/__init__.py", line 277, in connec
remote:     return CMySQLConnection(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 86, in __init__
remote:     self.connect(**kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1003, in connect
remote:     self._open_connection()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
remote:     sqlstate=exc.sqlstate)
remote: mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)
remote: 
remote: The above exception was the direct cause of the following exception
remote: 
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/bin/flask", line 8, in <module>
remote:     sys.exit(main())
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/cli.py", line 967, in main
remote:     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/cli.py", line 586, in main
remote:     return super(FlaskGroup, self).main(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/core.py", line 782, in main
remote:     rv = self.invoke(ctx)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
remote:     return _process_result(sub_ctx.command.invoke(sub_ctx))
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
remote:     return _process_result(sub_ctx.command.invoke(sub_ctx))
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
remote:     return ctx.invoke(self.callback, **ctx.params)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke
remote:     return callback(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
remote:     return f(get_current_context(), *args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
remote:     return __ctx.invoke(f, *args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke
remote:     return callback(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_migrate/cli.py", line 136, in upgrade
remote:     _upgrade(directory, revision, sql, tag, x_arg)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_migrate/__init__.py", line 96, in wrapped
remote:     f(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_migrate/__init__.py", line 271, in upgrade
remote:     command.upgrade(config, revision, sql=sql, tag=tag)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/alembic/command.py", line 294, in upgrade
remote:     script.run_env()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/alembic/script/base.py", line 490, in run_env
remote:     util.load_python_file(self.dir, "env.py")
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
remote:     module = load_module_py(module_id, path)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py
remote:     spec.loader.exec_module(module)
remote:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
remote:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:   File "migrations/env.py", line 90, in <module>
remote:     run_migrations_online()
remote:   File "migrations/env.py", line 75, in run_migrations_online
remote:     with connectable.connect() as connection:
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
remote:     return self._connection_cls(self, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
remote:     else engine.raw_connection()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2370, in raw_connection
remote:     self.pool.unique_connection, _connection
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
remote:     e, dialect, self
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
remote:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
remote:     raise exception
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
remote:     return fn()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
remote:     return _ConnectionFairy._checkout(self)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
remote:     fairy = _ConnectionRecord.checkout(pool)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
remote:     rec = pool._do_get()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
remote:     self._dec_overflow()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
remote:     with_traceback=exc_tb,
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
remote:     raise exception
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
remote:     return self._create_connection()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
remote:     return _ConnectionRecord(self)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
remote:     self.__connect(first_connect_check=True)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
remote:     pool.logger.debug("Error on connect(): %s", e)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
remote:     with_traceback=exc_tb,
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
remote:     raise exception
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
remote:     connection = pool._invoke_creator(self)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
remote:     return dialect.connect(*cargs, **cparams)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
remote:     return self.dbapi.connect(*cargs, **cparams)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/__init__.py", line 277, in connec
remote:     return CMySQLConnection(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 86, in __init__
remote:     self.connect(**kwargs)
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1003, in connect
remote:     self._open_connection()
remote:   File "/app/.heroku/python/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 236, in _open_connection
remote:     sqlstate=exc.sqlstate)
remote: sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)
remote: (Background on this error at: http://sqlalche.me/e/13/4xp6)
remote: Waiting for release.... failed.
```

**Comment by williambarberjr** [comment]
Following that link to get more info gives me the following details:

```
DatabaseError
Exception raised for errors that are related to the database itself, and not the interface or data being passed.

This error is a DBAPI Error and originates from the database driver (DBAPI), not SQLAlchemy itself.
```

**Comment by alesanchezr** [comment]
Hey @williambarberjr do you have MySQL properly configured?

This is the connection string proposed in the boilerplate: `DB_CONNECTION_STRING=mysql+mysqlconnector://root@localhost/example`

That means you need to have a database "example" on your localhost.
